# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

before_install:
  - tlmgr install opensans
  - tlmgr install wallpaper
  - tlmgr install eso-pic
  - tlmgr install slantsc
  - tlmgr install fancyhdr
  - tlmgr install hyperref
  - tlmgr install newunicodechar

after_success:
    - Rscript -e 'covr::codecov()'
