
# Install Pandoc
# source: https://github.com/krlmlr/r-appveyor/issues/82#issuecomment-261695154
before_test:
  - ps: >-
      if (-Not (Test-Path "C:\Program Files (x86)\Pandoc\")) {
        cinst pandoc
      }
  - ps: $env:Path += ";C:\Program Files (x86)\Pandoc\"
  - pandoc -v

environment:
  PATH: "%APPDATA%\\TinyTeX\\bin\\win32;%PATH%"


# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap
  # https://github.com/holgern/TUB_PhDThesisTemplate/blob/f1f36a42437966ea7037ac1496224f08d42308c0/appveyor.yml#L17
  # autoinstall latex packages (0=no, 1=autoinstall, 2=ask)
  # this adds this to the registry!
  - initexmf --set-config-value "[MPM]AutoInstall=1"
  - mpm --install=cm-super
  - mpm --update-db
  - mpm --update=fontspec
  - initexmf --update-fndb

cache:
  - C:\RLibrary
  - C:\Program Files (x86)\Pandoc\

# Adapt as necessary starting from here

build_script:
  - echo | tools\install-windows.bat
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
